spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: community_service
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    schemas: community_service
    default-schema: community_service
