server:
  port: 8083

spring:
  application:
    name: spring-member-community-service

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

logging:
  charset:
    console: UTF-8
  level:
    com.springmsa.membercommunityservice: debug
    org.springframework.security: debug
