CREATE TABLE community_posts (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_sub VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(5000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_community_posts_created_at
    ON community_posts (created_at DESC, post_id DESC);

CREATE INDEX idx_community_posts_owner
    ON community_posts (owner_sub, created_at DESC);
